### ISSUE TITLE
Ticket List

### ISSUE THREAD

**Issue by SolutionGroup** [SolutionGroup/FSmobile#1]
![fs-ricambim-ticketlist](https://cloud.githubusercontent.com/assets/2674665/7179537/472bb86c-e439-11e4-8252-607f452757c4.png)

**Comment by angeliniSG** [comment]
modifiche:
* la pick list diventa un tab dell'applicazione e quindi non abbiamo il pulsante
* la funzionalità di ricerca ed aggiunta ticket viene inglobata in questa pagina 
* il click su un ticket lo aggiunge alla pick list

TODO:
* ricerca di ticket non presenti in lista da aggiungere (necessita delle api); in caso di esito positivo lo aggiunge alla lista e lo evidenzia; in caso di esito negativo compare un messaggio di errore
