### ISSUE TITLE
Ticket Ricambi - List

### ISSUE THREAD

**Issue by SolutionGroup** [SolutionGroup/FSmobile#3]
![fs-ricambim-ticketricambi](https://cloud.githubusercontent.com/assets/2674665/7179559/90147c30-e439-11e4-89b3-cae159642382.png)

**Comment by angeliniSG** [comment]
Questa pagina non è più necessaria; le sue funzionalità sono state spostate o sulla lista ticket (#1) o nella pick list (#5)
