### ISSUE TITLE
Pick List

### ISSUE THREAD

**Issue by SolutionGroup** [SolutionGroup/FSmobile#5]
![fs-ricambim-picklist](https://cloud.githubusercontent.com/assets/2674665/7179597/fa92786e-e439-11e4-8544-399c3dd22c4f.png)

**Comment by SolutionGroup** [comment]
come interfaccia, farei qualcosa più di questo genere, con un aumento della dimensione di un singolo ticket per una maggiore visibilità e operatività. dai ragionamenti e i contatti col personale I ticket non dovrebbero essere molti contemporaneamente in lista (da 1 a 4 max). C'è sempre tempo per ridurre.
 
![image](https://cloud.githubusercontent.com/assets/2674665/7226233/2a68d74e-e747-11e4-882b-ea7801edd524.png)

**Comment by angeliniSG** [comment]
modifiche:
* inserita funzionalità di aggiungi ricambio (tramite bottone a comparsa effettuando lo slide a sx del ticket (testata))
* inserita funzionalità di cancellazione di ticket e relativi ricambi dalla pick list (tramite bottone a comparsa effettuando lo slide a sx del ticket (testata))
* inserita la funzionalità di cancellazione di un singolo ricambio dalla pick list (tramite bottone a comparsa effettuando lo slide a sx del ricambio)
* rimosso pulsante "aggiungi ticket" (si gestisce tramite il tab "lista ticket")

**Comment by angeliniSG** [comment]
TODO:
* funzionalità di "crea bolla" (deve contattare una web api che esegua i prelievi richiesti e rimuova il flag "richiesta ricambi" dal ticket + stampa della bolla)
